### PR TITLE
refactor: change folder name

### PR DESCRIPTION
**Pull request by Caixetadev**
This code has an error and probably won't run, I need you to do some tests after merging

This code in the `backend/internal/router/router.go` path is giving an error, reason: it is not finding the module `github.com/kevinanielsen/go-fast-cdn/frontend`.
I need you to go into the backend folder and run the command `go get github.com/kevinanielsen/go-fast-cdn/frontend` If you get an error, run this `go get github.com/kevinanielsen/go-fast-cdn/frontend@development`
image

### CODE REVIEW

**Comment by kevinanielsen** [comment]
While changes to the folder structure are needed to use best practices, I don't agree with this folder structure. There should not be definitive backend/ and frontend/ folders. Take a look at the folder structure of https://github.com/pocketbase/pocketbase and their use of the ui/ directory

**Comment by Caixetadev** [comment]
I understand, we have to see which pattern you want to follow. I'll send some repo:

[terraform](https://github.com/hashicorp/terraform)
[permify](https://github.com/Permify/permify)
[an example of monolith](https://github.com/powerman/go-monolith-example)
[steam pipe](https://github.com/turbot/steampipe)
[project  layout](https://github.com/golang-standards/project-layout)

Looking at these examples there really is no backend inside the backend folder

**Comment by kevinanielsen** [comment]
These patterns I like a lot.

**Comment by Caixetadev** [comment]
Do you want to keep the ui or website?

**Comment by kevinanielsen** [comment]
ui would be best

**Review by kevinanielsen — APPROVED** [review]
Looks good! I apologize for the long wait on me getting back to you.

**Pull request merged**
