### PR TITLE
feat(docker): Quickstart app with docker

### PR DESCRIPTION
**Pull request by amritupreti**
This PR adds a Dockerfile and docker-compose.yml to containerize the application. The Dockerfile sets up multi-stage builds for the front-end and back-end, while docker-compose.yml orchestrates container deployment with persistent storage for uploaded files and database data.

Key Changes:
Dockerfile: Multi-stage build for Node.js and Go applications.
docker-compose.yml: Manages service orchestration and persistence.

Instructions:
Build the Docker image:
docker build -t my-app .

Start the application:
docker-compose up -d

Please review and provide feedback.

### CODE REVIEW

**Comment by yunimoo** [comment]
I seem to be running into an error while testing these changes.
```
 > [server gowork 7/7] RUN go build -o /app/main .:
0.452 ui/embed.go:14:12: pattern build: no matching files found
------
failed to solve: process "/bin/sh -c go build -o /app/main ." did not complete successfully: exit code: 1
```

I believe that instead of going for this, we can potentially try to release an official docker image - rather than the user building it themselves. We can leave the docker-compose as an example for the user to use while deploying on their own environment.

@kevinanielsen, is this something that you would like to have? I could work on a pipeline to get official images for this project.

**Comment by amritupreti** [comment]
> I seem to be running into an error while testing these changes.
> 
> ```
>  > [server gowork 7/7] RUN go build -o /app/main .:
> 0.452 ui/embed.go:14:12: pattern build: no matching files found
> ------
> failed to solve: process "/bin/sh -c go build -o /app/main ." did not complete successfully: exit code: 1
> ```
> 
> I believe that instead of going for this, we can potentially try to release an official docker image - rather than the user building it themselves. We can leave the docker-compose as an example for the user to use while deploying on their own environment.
> 
> @kevinanielsen, is this something that you would like to have? I could work on a pipeline to get official images for this project.

I have just fixed it. You can try now. I forgot to copy the ui build into the build process of go.

**Comment by yunimoo** [comment]
> > I seem to be running into an error while testing these changes.
> > ```
> >  > [server gowork 7/7] RUN go build -o /app/main .:
> > 0.452 ui/embed.go:14:12: pattern build: no matching files found
> > ------
> > failed to solve: process "/bin/sh -c go build -o /app/main ." did not complete successfully: exit code: 1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I believe that instead of going for this, we can potentially try to release an official docker image - rather than the user building it themselves. We can leave the docker-compose as an example for the user to use while deploying on their own environment.
> > @kevinanielsen, is this something that you would like to have? I could work on a pipeline to get official images for this project.
> 
> I have just fixed it. You can try now. I forgot to copy the ui build into the build process of go.

Thanks, looks good for me

**Comment by amritupreti** [comment]
I have submitted a new pr. Docker is working now. I have just learned
github actions. I can help to create a pipeline.

**Comment by amritupreti** [comment]
I have removed previous pr. I had included both docs and features in that.
Now, I have separated both of them, and created separate PRs for both of
them. You can have a look.

**Pull request closed without merging**
