### PR TITLE
feat: add endpoint for getting data about a given document

### PR DESCRIPTION
**Pull request by kaiiorg**
Related to #75 

Adds endpoint at `/api/cdn/doc/:filename` that attempts to get relevant information for the requested document.

Example:
`GET http://localhost:8080/api/cdn/doc/resume.pdf`
returns
```json
{
  "download_url": "localhost:8080/api/cdn/download/docs/resume.pdf",
  "file_size": 68403,
  "filename": "resume.pdf"
}
```

Confirmed the `download_url` works by pasting it in a web browser

I have not yet written any documentation for this endpoint yet. Wanted to get initial feedback first.

### CODE REVIEW

**Comment by kaiiorg** [comment]
I've added the spec; I'll write some tests later today. Doesn't look like the project has any existing tests, am I correct?

**Comment by kaiiorg** [comment]
Wrote tests covering every case except for when os.Stat fails for some reason other than the file not existing. Not sure how I'd force that to happen on demand.

**Comment by kaiiorg** [comment]
I think this is ready for review, aside from maybe adding another make target and a github actions job to run the tests. I can do that if you'd like.

**Comment by kevinanielsen** [comment]
That would be amazing - I am struggling a bit with testing, as I am new to Go. Any contributions would be great! I will review you work for this issue now :)

**Review by kevinanielsen — APPROVED** [review]
Looks great!

**Comment by kaiiorg** [comment]
No problem on the testing; I'll open another issue for setting up the make target and github actions job and I'll work on that.

**Pull request merged**
