### PR TITLE
added delete apis

### PR DESCRIPTION
**Pull request by ankit-pn**
restructured the database package - removed addDoc.go and addImage.go and included doc.go and image.go, these two file should contain logic of every database operation.

renamed handleDocsUpload.go to handleDocUpload.go - since we are dealing with 1 file at a time, it is better to keep doc instead of docs

modified - api.go to include delete endpoint

added HandleImageDelete and HandleDocDelete Method to deal with deletion

### CODE REVIEW

**Comment by kevinanielsen** [comment]
Just tested it on my machine and everything runs perfectly - Thanks for your contribution!
If you want to contribute again that would be great! 
Please try doing it in more commits next time though :)

**Review by kevinanielsen — APPROVED** [review]

**Comment by ankit-pn** [comment]
This looks like a very interesting project to me. I would love to contribute again to this project, it would be great to add some more enhancement issues to this project, maybe we can try adding some milestone like implementing edge server for cdn and implementing a caching mechanism to it.

Anyway thanks.

**Comment by kevinanielsen** [comment]
@ankit-pn Sounds like fun features - I am definitely open to ideas, the most important thing for me is that it needs to be easy to use, and easy to host!

**Comment by ankit-pn** [comment]
Ok thanks, maybe I will add some features/ suggestions at issues in future. We will discuss it and if it sounds good then try to implement it.

**Comment by kevinanielsen** [comment]
@ankit-pn Great!

**Pull request merged**
