### PR TITLE
feat: Add API endpoint for renaming files

### LINKED ISSUE #18: [Feature] Add API endpoint for renaming files

### PR DESCRIPTION
**Pull request by webstradev**
Renames are done with simple update statesments using GORM.

I follow the same router grouping pattern as you have done previously for upload and suggest we do the same for delete @ankit-pn .  Unless you would like to suggest a different structure, I'm happy to adjust.

Closes #18

### CODE REVIEW

**Comment by ankit-pn** [comment]
I have done some restructure change of database package. Other than that everything is good.

**Comment by ankit-pn** [comment]
Hey I think you are doing rename only in database. We need to do it in filesystem also?

**Review by kevinanielsen — APPROVED** [review]
Looks great!

**Comment by kevinanielsen** [comment]
Everything looks good! If you decide to contribute again it would be very welcome!

**Comment by kevinanielsen** [comment]
> Hey I think you are doing rename only in database. We need to do it in filesystem also?

Since the database finds the files via checksum and not filename, it should be fine to only rename using database.

**Comment by webstradev** [comment]
@kevinanielsen As ankit pointed out renaming the actual file in the fs was missing, I have just pushed that up now would you like me to reopen the pull request

**Comment by kevinanielsen** [comment]
@webstradev Yes please, that would be great. @ankit-pn you were right, it was missing :)

**Comment by webstradev** [comment]
> @webstradev Yes please, that would be great. @ankit-pn you were right, it was missing :)

Done
https://github.com/kevinanielsen/go-fast-cdn/pull/30

**Pull request merged**
