### PR TITLE
[CI] Add make target and actions job to execute tests

### PR DESCRIPTION
**Pull request by kaiiorg**
Relates to #84 
- Adds make target to execute tests; `make test`
- Modified readme to mention the new make target
- Added github actions job to execute tests and upload a coverage report

### CODE REVIEW

**Comment by kaiiorg** [comment]
Not sure why that's failing; I'll work on fixing it. Might take me a few attempts

**Comment by kevinanielsen** [comment]
It's failing becuase the frontend has not been build - The pnpm build script needs to be run for the go files to compile.
It looks great so far otherwise!

**Comment by kaiiorg** [comment]
Ah, that explains that. I'll get that fixed. Thanks!

**Comment by kaiiorg** [comment]
Ok, I think we're good to go now. The job uploads the coverage report HTML file, though I'm sure there are better ways of doing it. Baby steps : P

**Comment by kevinanielsen** [comment]
This looks great! Merging now! - Will the HTML file be served somewhere so it can be found?

**Review by kevinanielsen — APPROVED** [review]
LGTM

**Pull request merged**
